### ISSUE TITLE
Replace `eslint-plugin-node` by `eslint-plugin-n`

### ISSUE THREAD

**Issue by Julien-R44** [Shinigami92/eslint-define-config#129]
Hey ! 

I just discovered the project, and it's really great to make custom eslint configurations. Really, an incredible job, well done 👏 

I realized that you added support for `eslint-plugin-node`. which is cool, but this plugin has not been maintained for a while. People are starting to migrate to [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n#readme) which is a fork. And it's possible that a repo transfer will be done soon : 

https://github.com/mysticatea/eslint-plugin-node/issues/341

I don't know exactly all the changes between the two repositories, all I know is that many things are in common.

So we have two choices, either totally drops the first one for the second plugin, or support both. I would be more in favor of dropping `eslint-plugin-node`.

I can't promise anything because I'm a little short on time right now, but I'm willing to propose a PR after I get your opinion.

Thanks again for this fabulous project which is a life saver!

**Comment by Shinigami92** [comment]
For now, I would just prefer to support both
So just add the new plugin and run the generate script (see package.json scripts)
Then ignore ALL errors that were thrown by the generate tool and revert all non plugin related changes
Then check if everything coming from the plugin looks fine

**Comment by Julien-R44** [comment]
Okay cool, thanks. I'm going to try to watch it this weekend.

I'm going to check out the repo a bit to see how the generation works and how much of it you have to write by hand.

Because there are some other eslint plugins that I'd like to have support for. If I can add that in passing, that would be awesome
