### ISSUE TITLE
Unclear docs on how to use this with FlatESLintConfig

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [Shinigami92/eslint-define-config#157]
## PROBLEM

I'm trying to use this in my FlatConfig, but without success. Looking at the latest PRs, this should be supported, but in the docs there is no such mention, even less so an explanation for complex usage.
For reference, this is where i'm trying to use it: https://github.com/AndreaPontrandolfo/sheriff/blob/master/configs/eslint.config.js

## PROPOSED SOLUTION

Expand the docs on how to use this with the FlatConfig, also for complex usage.

**Comment by Shinigami92** [comment]
@sxzz is responsible for the flat-config support

**Comment by sxzz** [comment]
It's pretty easy. Use `defineFlatConfig` then works
