### ISSUE TITLE
parserOptions.project should be nullable

### ISSUE THREAD

**Issue by Dimava** [Shinigami92/eslint-define-config#175]
Trying to make ESLint lint AND ts-check itself, I encountered the error
> Parsing error: ESLint was configured to run on `<tsconfigRootDir>/.eslintrc.cjs` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
> However, that TSConfig does not include this file. Either:
> - Change ESLint's list of included files to not include this file
> - Change that TSConfig to include this file
> - Create a new TSConfig that includes this file and include it in your parserOptions.project
> See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-fileeslint
> > Alternatively, you can add `parserOptions: { project: null }` to an override for the files you wish to exclude. Note that `{ project: undefined }` will not work.

Which could be fixed with
```
  overrides: [{
    "files": [".eslintrc.cjs"],
    parserOptions: { project: null /* <- add nul*/ },
  }],
```
Which requires parserOptions.project to be nullable as per above link

**Comment by Shinigami92** [comment]
https://github.com/Shinigami92/eslint-define-config/commit/5b73f495b30b85450f2537b8238d10e3eeb9f071
