### ISSUE TITLE
Add supports for `eslint-plugin-unicorn`

### ISSUE THREAD

**Issue by fisker** [Shinigami92/eslint-define-config#55]
Wow, found this is so cool, can we add support for  [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)?

**Comment by Shinigami92** [comment]
> can we add support for `eslint-plugin-unicorn`

Sure! It is highly extendable :slightly_smiling_face: 

There is already support for e.g. [jsdoc](https://github.com/Shinigami92/eslint-define-config/tree/main/src/rules/jsdoc) and other stuff.

Do you want to try it and open a PR?

Will grant you write access so you don't need to fork

There is also a script to generate a `rule`

https://github.com/Shinigami92/eslint-define-config/blob/435ca836125e7228ad8afce9ee3909207c309eb1/package.json#L13

**Comment by fisker** [comment]
> Do you want to try it and open a PR?

Sorry, but I don't use ts at all.

**Comment by Shinigami92** [comment]
> Sorry, but I don't use ts at all.

I will not hurt you 😏
Or will it? :eyes: 

---

Could you write your top 10 most used rules of `eslint-plugin-unicorn`?
Then I could add these.
The generation is not that automated :slightly_frowning_face: So I need to hand-write every rule on its own...
That's why I mostly support first the rules that are common used.

**Comment by fisker** [comment]
I had a quick look on the script, you're hard coding the docs links, why not load the rule, links exists in their meta.

Can these options generated from the schema?(Just an idea.)

**Comment by Shinigami92** [comment]
> I had a quick look on the script, you're hard coding the docs links, why not load the rule, links exists in their meta.
> 
> Can these options generated from the schema?(Just an idea.)

Every plugin has a different kind of structure and generating them automatically would not result in such good types than with handcrafted types and JSDoc.

**Comment by fisker** [comment]
> Every plugin has a different kind of structure

Can you explain?

**Comment by Shinigami92** [comment]
In example https://github.com/aotaduy/eslint-plugin-spellcheck/blob/master/rules/spell-checker.js doesn't have a link to the docs I manually added

https://github.com/Shinigami92/eslint-define-config/blob/435ca836125e7228ad8afce9ee3909207c309eb1/src/rules/spellcheck/spell-checker.d.ts#L68

And e.g. https://github.com/Shinigami92/eslint-define-config/blob/435ca836125e7228ad8afce9ee3909207c309eb1/src/rules/spellcheck/spell-checker.d.ts#L22-L26

this was copied from the docs

https://github.com/aotaduy/eslint-plugin-spellcheck#configuration-options

**Comment by fisker** [comment]
I see, but we can still use script to generate them, and modify if nessary.

**Comment by Shinigami92** [comment]
Please feel free to create a draft. And feel free to do that in plain js for now.
If it works I can convert it to ts later on.

Just create a branch/PR and feel free to escalate :smile:

**Comment by fisker** [comment]
Okay, I'll try, going to sleep now.

**Comment by Shinigami92** [comment]
> Okay, I'll try, going to sleep now.

Added you on Discord :eyes:

**Comment by Shinigami92** [comment]
Finally I found some free time to work on an automation to generate the rules

I added support for your requested plugin :tada: 

https://github.com/Shinigami92/eslint-define-config/commit/cabba8d4f91ed4ce01af311fdfe6a0b4069c6804

Will be released in `1.1.0`
