### ISSUE TITLE
node Version too high 

### ISSUE THREAD

**Issue by SharepointPlus** [Shinigami92/eslint-define-config#72]
node Version too high

**Comment by heartbeatLV** [comment]
Uning yarn: 
```
error eslint-define-config@1.2.1: The engine "node" is incompatible with this module. Expected version ">= 16.9.0". Got "15.11.0"
error Found incompatible module.
```

**Comment by Shinigami92** [comment]
Can you update your node to the latest LTS?

**Comment by heartbeatLV** [comment]
first thank you for the brilliant package
updating node resolve the issue
I was only add a clarification to the issue

**Comment by Shinigami92** [comment]
I set that to 16.9 to be compatible with `corepack`, so I will close this issue now
